vies_application.application_form:
  path: '/ansogning'
  defaults:
    _form: '\Drupal\vies_application\Form\ApplicationForm'
    _title: 'Application'
  requirements:
    _access: 'TRUE'

vies_application.application_form_success:
  path: '/ansogning/success'
  defaults:
    _controller: '\Drupal\vies_application\Controller\ApplicationController::success'
    _title: 'Application has been submitted'
  requirements:
    _access: 'TRUE'

vies_application.application_form_error:
  path: '/ansogning/error'
  defaults:
    _controller: '\Drupal\vies_application\Controller\ApplicationController::error'
    _title: 'Application submission failed'
  requirements:
    _access: 'TRUE'
